# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G7O5nGvH3rYNOmscCJ-TV80g4PjSpBMG
"""

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
from tabulate import tabulate

def compute_rsi(data, window=14):
    delta = data['Close_AAPL'].diff()   #stock ticker symbol

    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)
    avg_gain = gain.rolling(window=window, min_periods=window).mean()
    avg_loss = loss.rolling(window=window, min_periods=window).mean()
    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))
    return rsi

df = yf.download('AAPL', period='6mo', interval='1d')   #stock ticker symbol

df.columns = ['_'.join(col).strip() if isinstance(col, tuple) else col for col in df.columns.values]

df['RSI'] = compute_rsi(df)

print(tabulate(df[['Close_AAPL', 'RSI']].dropna().round(2).tail(), headers='keys', tablefmt='pretty'))

fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12,8), sharex=True)
ax1.plot(df.index, df['Close_AAPL'], label='Close Price')   #stock ticker symbol
ax1.set_title('Apple (AAPL) Close Price')   #stock ticker symbol
ax1.set_ylabel('Price (£)')
ax1.legend()
ax1.grid(True)

ax2.plot(df.index, df['RSI'], label='RSI', color='orange')
ax2.axhline(70, color='red', linestyle='--', label='Overbought (70)')
ax2.axhline(30, color='green', linestyle='--', label='Oversold (30)')   #used traditional 70 30 RSI value
ax2.set_title('Relative Strength Index (RSI)')
ax2.set_ylabel('RSI Value')
ax2.set_xlabel('Date')
ax2.legend()
ax2.grid(True)

plt.tight_layout()
plt.show()